Set manually web path and external port of sftpgo
NethServer/ns8-webserver pull request #18
Opened 2022-11-10 17:04 UTC by stephdl

2022-11-15 08:29 UTC, andre8244 requested changes
Just a couple of minor changes

2022-11-15 08:29 UTC, andre8244 commented on imageroot/actions/configure-module/02_validate_sftp_port
> +sock.close()
Let's move `sock.close()` at line 28 just after assigning `result` variabile, otherwise the script will exit before closing the socket

2022-11-15 08:29 UTC, andre8244 commented on imageroot/actions/configure-module/60sftpgo_create_secret
> +
Double empty line :)

2022-11-15 08:29 UTC, andre8244 commented on ui/public/i18n/language.json
> +    "sftpgo_not_running": "sftpgo is not configured",
```suggestion
    "sftpgo_not_running": "SFTPGo is not configured",
```
Just a minor suggestion to use the correct case for "SFTPGo"

2022-11-15 08:29 UTC, andre8244 commented on ui/public/i18n/language.json
> +    "configure_sftpgo": "Configure SFTPGO"
```suggestion
    "configure_sftpgo": "Configure SFTPGo"
```

2022-11-15 08:29 UTC, andre8244 commented on ui/public/i18n/language.json
> +    "sftp_tcp_port_number_gte": "The TCP port must be greater than 1024",
```suggestion
    "sftp_tcp_port_number_gte": "The TCP port must be greater or equal than 1024",
```

2022-11-15 08:29 UTC, andre8244 commented on ui/public/i18n/language.json
> +    "sftp_tcp_port_number_lte": "The TCP port must be smaller than 65535",
```suggestion
    "sftp_tcp_port_number_lte": "The TCP port must be lower or equal than 65535",
```

2022-11-15 08:29 UTC, andre8244 commented on ui/src/views/Status.vue
> +                <NsButton kind="ghost" :icon="Launch20" @click="goToAppPage(instanceName, 'settings')">
```suggestion
                <NsButton kind="ghost" :icon="ArrowRight20" @click="goToAppPage(instanceName, 'settings')">
```
We usually use `Launch20` icon only for external links

2022-11-15 15:01 UTC, stephdl commented on imageroot/actions/configure-module/02_validate_sftp_port
> +sock.close()
done

2022-11-15 15:02 UTC, stephdl commented on imageroot/actions/configure-module/60sftpgo_create_secret
> +
done

2022-11-15 15:02 UTC, stephdl commented on imageroot/actions/configure-module/02_validate_sftp_port
> +sock.close()
done

2022-11-15 15:21 UTC, DavidePrincipi commented on build-images.sh
> +    --label="org.nethserver.authorizations=node:fwadm traefik@any:routeadm" \
:grey_question: does the module need to admin HTTP routes on ANY cluster of the node?

```suggestion
    --label="org.nethserver.authorizations=node:fwadm traefik@node:routeadm" \
```

2022-11-15 16:16 UTC, stephdl commented on imageroot/actions/configure-module/02_validate_sftp_port
> +result = sock.connect_ex(('127.0.0.1',int(port)))
done

2022-11-16 11:23 UTC, DavidePrincipi commented on imageroot/actions/configure-module/02_validate_sftp_port
> +    sock.bind(('127.0.0.1', int(port)))
The port must be free on ANY IPv4 (at least) address of the server. In a perfect world the test should be repeated on a distinct socket, with family AF_INET6
```suggestion
    sock.bind(("", int(port)))
```

2022-11-16 11:23 UTC, DavidePrincipi commented on imageroot/actions/configure-module/02_validate_sftp_port
> +except Exception as ex:
Selectively catch only what we expect. Raise again what we don't expect.

:warning: Add `import errno`

```suggestion
except OSError as ex:
    if ex.errno != errno.EADDRINUSE:
        raise
```

2022-11-16 16:44 UTC, stephdl commented
@andre8244 @DavidePrincipi 

we test ipv6 (opened port) and we have a switch to disable SFTPGo (check pictures in the PR description

2022-11-17 07:41 UTC, andre8244 reviewed
Another minor enhancement: let's edit `common.enabled` and `common.disabled` strings inside `language.json` using uppercase:
```json
"enabled": "Enabled",
"disabled": "Disabled"
```

2022-11-17 07:41 UTC, andre8244 commented on ui/public/i18n/language.json
> +    "sftpgo_switch": "Enable SFTPGo",
```suggestion
    "sftpgo_switch": "SFTPGo",
```

2022-11-17 07:41 UTC, andre8244 commented on ui/public/i18n/language.json
> +    "sftpgo_explanation_tooltips": "SFTPGo is a service to provide an user interface and a sftp service for uploading your websites"
```suggestion
    "sftpgo_explanation_tooltips": "SFTPGo provides a user interface and a SFTP service for uploading your websites"
```

2022-11-17 10:11 UTC, DavidePrincipi commented on imageroot/actions/configure-module/60sftpgo_create_secret
> +    os.chmod('sftpgo.conf.d/API_KEY', 0o600)
1. chmod() is not atomic. Before creating a file with a secret, set the process umask instead.
2. using a Python context helps to close the file properly

```suggestion
    oldmask = os.umask(0o77)
    with open('sftpgo.conf.d/API_KEY', "w") as fkey:
        fkey.write(key["key"])
    os.umask(oldmask)
```

2022-11-17 10:11 UTC, DavidePrincipi commented on imageroot/actions/get-configuration/20read
> +import subprocess
Is it still used?

```suggestion
```

2022-11-17 10:11 UTC, DavidePrincipi commented on imageroot/actions/restore-module/60systemd
> +    subprocess.run(["systemctl", "--user", "enable","--now", "sftpgo.service"])
agent.run_helper(), here too...

2022-11-17 13:53 UTC, stephdl commented on imageroot/actions/configure-module/60sftpgo_create_secret
> +# NethServer is free software: you can redistribute it and/or modify
old file existing before the new template, I cannot modify all files with the new template

2022-11-17 14:04 UTC, stephdl commented on imageroot/actions/get-configuration/20read
> +import subprocess
done

2022-11-17 14:11 UTC, stephdl commented on imageroot/actions/restore-module/60systemd
> +    subprocess.run(["systemctl", "--user", "enable","--now", "sftpgo.service"])
done

2022-11-17 14:12 UTC, stephdl commented on imageroot/actions/configure-module/50start_services
> +subprocess.run(["systemctl", "--user", "enable","--now", "webserver.service"])
done

2022-11-17 14:58 UTC, DavidePrincipi approved these changes

2022-11-17 16:01 UTC, merged