Update SFTP TCP Port placeholder and type
NethServer/ns8-webserver pull request #49
Opened 2023-12-04 10:55 UTC by stephdl

This pull request updates the SFTP TCP Port placeholder and type in the Settings view. The placeholder has been changed to "e.g. 3092" and the input type has been set to "number". This makes it clearer for users to enter the desired port number. Additionally, the translation for the tooltip has been updated to include the actual port number entered by the user. This improves the user experience and provides better guidance when configuring the SFTP TCP Port.

2023-12-04 15:32 UTC, andre8244 requested changes

2023-12-04 15:32 UTC, andre8244 commented on ui/src/views/Settings.vue
> +                placeholder="e.g. 3092"
Let's use an i18n string

2023-12-04 15:32 UTC, andre8244 commented on ui/src/views/Settings.vue
> +                      $t('settings.sftp_tcp_port_tips', {port: sftp_tcp_port})
I fear the tooltip is unclear if the user opens it while port is an empty string.. It would show `... sftp -P  user@hostname`

2023-12-04 16:58 UTC, stephdl commented on ui/src/views/Settings.vue
> +                      $t('settings.sftp_tcp_port_tips', {port: sftp_tcp_port})
what to do then, you are right

2023-12-05 08:44 UTC, andre8244 commented on ui/src/views/Settings.vue
> +                      $t('settings.sftp_tcp_port_tips', {port: sftp_tcp_port || 'tcp_port'})
```suggestion
                      $t('settings.sftp_tcp_port_tips', {port: sftp_tcp_port || '<tcp_port>'})
```

2023-12-05 09:52 UTC, stephdl commented on ui/src/views/Settings.vue
> +                      $t('settings.sftp_tcp_port_tips', {port: sftp_tcp_port || 'tcp_port'})
we cannot `<>` because it is interpreted as html, I will commit with `{}`

2023-12-05 13:49 UTC, andre8244 approved these changes

2023-12-06 08:08 UTC, merged